### ISSUE TITLE
Examples of banners/creatives

### ISSUE THREAD

**Issue by ctrlbrk42** [dark-kitt/HTML5-Banner-Creator#1]
Hi,

Your project looks great on paper.  Could you please share a few examples of the banners/creatives created using this project, as part of your github description?  So that prospects can see the capability of the package before spending the time setting it up?

**Comment by dark-kitt** [comment]
Hey man,

thanks for the great response and sorry for the late reply. I guess you have to setting up the "banner-creator", that you'll really get what are the goals of this small application. And actually it doesn't take that long (max. ~ 20 min). My idea was to create a helper, where you can develop banners in your own environment, which you are use to as Frontend. 

Take care.
